import os

# Base paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATA_DIR = os.path.join(BASE_DIR, "data")
MODEL_DIR = os.path.join(BASE_DIR, "models")
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs")
RESULTS_DIR = os.path.join(BASE_DIR, "results")
os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(OUTPUTS_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)

# Our two CSV files
FAKE_PATH = os.path.join(DATA_DIR, "Fake.csv")
TRUE_PATH = os.path.join(DATA_DIR, "True.csv")

MODEL_PATH = os.path.join(MODEL_DIR, "hybrid_model.h5")
TOKENIZER_PATH = os.path.join(MODEL_DIR, "tokenizer.pkl")

# Model v2 paths for safe, uncorrupted retraining
MODEL_V2_PATH = os.path.join(MODEL_DIR, "hybrid_model_v2.h5")
TOKENIZER_V2_PATH = os.path.join(MODEL_DIR, "tokenizer_v2.pkl")

# ---------------------------------------------------------------------------
# Phase 4 — Processed / clean dataset paths
# These are generated by src/prepare_dataset.py and must NOT be committed
# if the raw CSVs are the source of truth.
# Raw CSVs (Fake.csv, True.csv) are NEVER modified.
# ---------------------------------------------------------------------------
PROCESSED_DIR       = os.path.join(DATA_DIR, "processed")
TRAIN_CSV           = os.path.join(PROCESSED_DIR, "train.csv")
VAL_CSV             = os.path.join(PROCESSED_DIR, "val.csv")
TEST_CSV            = os.path.join(PROCESSED_DIR, "test.csv")
DATASET_STATS_JSON  = os.path.join(PROCESSED_DIR, "dataset_stats.json")
SPLIT_META_JSON     = os.path.join(PROCESSED_DIR, "split_metadata.json")
os.makedirs(PROCESSED_DIR, exist_ok=True)

# Text preprocessing / tokenization
MAX_WORDS = 20000       # vocabulary size
MAX_LEN = 300           # max tokens per news article

# Split ratios
TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15

# Training hyperparameters
TEST_SIZE = 0.15
RANDOM_STATE = 42
BATCH_SIZE = 64
EPOCHS = 5
EMBEDDING_DIM = 128

# ---------------------------------------------------------------------------
# Prediction uncertainty bounds — PROVISIONAL (Phase 3)
#
# These bounds define the prob_fake interval that triggers an UNCERTAIN label.
# They are NOT statistically calibrated: no proper held-out validation set
# exists yet (known Phase 4 issue — data leakage from full-dataset tokenizer
# fitting).  The values are a structural placeholder only.
#
# Distribution probe result (400 samples, Phase 3):
#   - 0/400 samples fall in [0.30, 0.70]   → model is extremely bimodal
#   - Accuracy @0.5 threshold = 99.75%
#   - In practice, UNCERTAIN will almost never fire on real news text
#
# These values MUST be re-determined after Phase 5 retraining + calibration
# on a proper held-out validation set.
# ---------------------------------------------------------------------------
UNCERTAINTY_ENABLED = True          # Set False to disable the UNCERTAIN label entirely
UNCERTAINTY_LOW     = 0.40          # PROVISIONAL — not yet calibrated
UNCERTAINTY_HIGH    = 0.60          # PROVISIONAL — not yet calibrated
